Hide address and selector
software-mansion/cairo-profiler pull request #41
Opened 2024-03-01 13:50 UTC by war-in

The `--show-details` flag has been introduced

2024-03-01 13:59 UTC, war-in commented on crates/cairo-profiler/tests/e2e.rs
tests are swapped (`test_case` needs to be at the bottom of the file because it creates a mod and clippy throws warnings)

2024-03-01 16:26 UTC, piotmag769 requested changes

2024-03-01 16:26 UTC, piotmag769 commented on crates/cairo-profiler/src/main.rs
> +    /// Show contract address and function selector
```suggestion
    /// Show contract addresses and function selectors in a trace tree
```

2024-03-01 16:26 UTC, piotmag769 commented on crates/cairo-profiler/src/trace_reader.rs
> +    function_name: String,
We shouldn't change this struct, we should still require address and selector and make contract name and function name optional. A good example of that are fork tests for forge, which won't generate contract names and function names.

2024-03-04 10:48 UTC, piotmag769 approved these changes

2024-03-04 10:48 UTC, piotmag769 commented on crates/cairo-profiler/src/trace_reader.rs
> +    function_name: String,
Add a comment explaining the logic pls

2024-03-04 12:37 UTC, merged